version: '3.8'

services:
  ts3-bot:
    container_name: teamspeak-join-bot
    image: ts3-bot
    environment:
      - TS3_HOST=127.0.0.1
      - TS3_USERNAME=bot
      - TS3_PWD=strongpassword
      - TELEGRAM_TOKEN=TOKEN
      - TELEGRAM_CHAT_ID=12345
    networks:
      tsbot-net:
        ipv4_address: 172.20.0.16
    restart: unless-stopped

networks:
  tsbot-net:
    name: your-teamspek-3-server-network
    external: true
